add_rules("mode.debug", "mode.release")
add_rules("qt.widgetapp")

target("ZoneTracer")
set_kind("binary")

add_files("topicData/ZoneMasterCanMessageDataSubscriber.cpp")
add_files("topicData/ZoneMasterCanMessageDataSubscriber.cpp")
add_files("topicData/ZoneMasterCanParserSubscriber.cpp")
add_files("topicData/ZoneMasterData.cxx")
add_files("topicData/ZoneMasterDataPubSubTypes.cxx")
add_files("topicData/ZoneMasterLinMessageDataSubscriber.cpp")
add_files("topicData/ZoneMasterLinParserDataSubscriber.cpp")
add_files("topicData/ZoneMasterSomeipDataSubscriber.cpp")

add_files("QtWidgetsApplication1.qrc")
add_files("columnfilter.h")
add_files("dialog/configdialog.h")
add_files("LineEditFilter.h")
add_files("multiThread.h")
add_files("QtWidgetsApplication1.h")
add_files("topicData/ZoneMasterSomeipDataCallingListener.h")
add_files("topicData/ZoneMasterCanMessageDataListener.h")
add_files("topicData/ZoneMasterSomeipDataEthFrameListener.h")
add_files("topicData/ZoneMasterSomeipDataSDListener.h")
add_files("topicData/ZoneMasterCanParserListener.h")
add_files("topicData/ZoneMasterLinParserDataListener.h")
add_files("topicData/ZoneMasterLinMessageDataListener.h")
add_files("topicData/ZoneMasterSomeipDataPackageListener.h")
add_files("topicData/ZoneMasterSomeipDataStateListener.h")
add_files("treemodel.h")
add_files("usagedialog.h")

add_files("columnfilter.cpp")
add_files("dialog/configdialog.cpp")
add_files("multiThread.cpp")
add_files("TraceTreeWidgetItem.cpp")
add_files("treeitem.cpp")
add_files("treemodel.cpp")
add_files("usagedialog.cpp")
add_files("QtWidgetsApplication1.cpp")
add_files("main.cpp")

-- add_cflags("-fPIC")
add_cxflags("-mavx2 -fPIC")

add_includedirs(".")
add_includedirs("/usr/include")
add_includedirs("/usr/local/include")
add_includedirs("/usr/local/include/fastrtps/")
add_includedirs("/usr/local/include/fastrtps/common/")
add_includedirs("/usr/local/include/fastrtps/utils/")
add_includedirs("/usr/local/include/fastcdr/")
add_includedirs("/usr/local/include/fastcdr/cdr/")
add_includedirs("/usr/local/include/fastcdr/exceptions/")
add_includedirs("/opt/Qt5.14.2/5.14.2/gcc_64/include/")
add_includedirs("/opt/Qt5.14.2/5.14.2/gcc_64/include/QtCore/")
add_includedirs("/opt/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets/")
add_includedirs("/opt/Qt5.14.2/5.14.2/gcc_64/include/QtGui/")
add_includedirs("/opt/Qt5.14.2/5.14.2/gcc_64/mkspecs/linux-g++")
add_includedirs("/usr/include/libdrm")

add_links("Qt5Widgets", "Qt5Core", "Qt5Gui")
add_links("fastrtps", "fastcdr")
add_linkdirs("/opt/Qt5.14.2/5.14.2/gcc_64/lib/")
add_ldflags("-L/usr/local/lib", "-lpthread", { force = true })
add_ldflags("-L/usr/lib", "-lfoonathan_memory-0.7.3", { force = true })
